In [91]:
import pandas as pd 
import json
import numpy as np
from pandas.io.json import json_normalize

In [75]:

#json.load((open('//Users//zoegong//Downloads//data_wrangling_json//data//world_bank_projects.json')))
#sample_json_df = pd.read_json('data/world_bank_projects_less.json')
df=pd.read_json('//Users//zoegong//Downloads//data_wrangling_json//data//world_bank_projects.json',lines=False)
df

,sector,supplementprojectflg,projectfinancialtype,prodline,mjtheme,idacommamt,impagency,project_name,mjthemecode,closingdate,...,majorsector_percent,board_approval_month,theme_namecode,countryname,url,source,projectstatusdisplay,ibrdcommamt,sector_namecode,_id
0,"[{'Name': 'Primary education'}, {'Name': 'Seco...",N,IDA,PE,[Human development],130000000,MINISTRY OF EDUCATION,Ethiopia General Education Quality Improvement...,"8,11",2018-07-07T00:00:00Z,...,"[{'Percent': 46, 'Name': 'Education'}, {'Perce...",November,"[{'code': '65', 'name': 'Education for all'}]",Federal Democratic Republic of Ethiopia,http://www.worldbank.org/projects/P129828/ethi...,IBRD,Active,0,"[{'code': 'EP', 'name': 'Primary education'}, ...",{'$oid': '52b213b38594d8a2be17c780'}
1,[{'Name': 'Public administration- Other social...,N,OTHER,RE,"[Economic management, Social protection and ri...",0,MINISTRY OF FINANCE,TN: DTF Social Protection Reforms Support,"1,6",NaN,...,"[{'Percent': 70, 'Name': 'Public Administratio...",November,"[{'code': '24', 'name': 'Other economic manage...",Republic of Tunisia,http://www.worldbank.org/projects/P144674?lang=en,IBRD,Active,0,"[{'code': 'BS', 'name': 'Public administration...",{'$oid': '52b213b38594d8a2be17c781'}
2,[{'Name': 'Rural and Inter-Urban Roads and Hig...,Y,IDA,PE,"[Trade and integration, Public sector governan...",6060000,MINISTRY OF TRANSPORT AND COMMUNICATIONS,Tuvalu Aviation Investment Project - Additiona...,"5,2,11,6",NaN,...,"[{'Percent': 100, 'Name': 'Transportation'}]",November,"[{'code': '47', 'name': 'Regional integration'...",Tuvalu,http://www.worldbank.org/projects/P145310?lang=en,IBRD,Active,0,"[{'code': 'TI', 'name': 'Rural and Inter-Urban...",{'$oid': '52b213b38594d8a2be17c782'}
3,[{'Name': 'Other social services'}],N,OTHER,RE,"[Social dev/gender/inclusion, Social dev/gende...",0,LABOR INTENSIVE PUBLIC WORKS PROJECT PMU,Gov't and Civil Society Organization Partnership,"7,7",NaN,...,"[{'Percent': 100, 'Name': 'Health and other so...",October,"[{'code': '57', 'name': 'Participation and civ...",Republic of Yemen,http://www.worldbank.org/projects/P144665?lang=en,IBRD,Active,0,"[{'code': 'JB', 'name': 'Other social services'}]",{'$oid': '52b213b38594d8a2be17c783'}
4,[{'Name': 'General industry and trade sector'}...,N,IDA,PE,"[Trade and integration, Financial and private ...",13100000,MINISTRY OF TRADE AND INDUSTRY,Second Private Sector Competitiveness and Econ...,"5,4",2019-04-30T00:00:00Z,...,"[{'Percent': 50, 'Name': 'Industry and trade'}...",October,"[{'code': '45', 'name': 'Export development an...",Kingdom of Lesotho,http://www.worldbank.org/projects/P144933/seco...,IBRD,Active,0,"[{'code': 'YZ', 'name': 'General industry and ...",{'$oid': '52b213b38594d8a2be17c784'}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"[{'Name': 'General agriculture, fishing and fo...",N,OTHER,RE,"[Financial and private sector development, Soc...",0,THE COMPETITIVENESS COMPANY,Technological Scale Up for Youth-led Urban Orn...,"4,7",2013-08-31T00:00:00Z,...,"[{'Percent': 50, 'Name': 'Agriculture, fishing...",August,"[{'code': '40', 'name': 'Regulation and compet...",Jamaica,http://www.worldbank.org/projects/P127299/tech...,IBRD,Closed,0,"[{'code': 'AZ', 'name': 'General agriculture, ...",{'$oid': '52b213b38594d8a2be17c96f'}
496,[{'Name': 'Central government administration'}...,N,IDA,PE,"[Human development, Trade and integration, Pub...",20000000,MINISTRY OF FINANCE,Lao Eight Poverty Reduction Support,"8,5,2,8",2012-12-31T00:00:00Z,...,"[{'Percent': 36, 'Name': 'Public Administratio...",August,"[{'code': '63', 'name': 'Child health'}, {'cod...",Lao People's Democratic Republic,http://www.worldbank.org/projects/P125298/lao-...,IBRD,Closed,0,"[{'code': 'BC', 'name': 'Central government ad...",{'$oid': '52b213b38594d8a2be17c970'}
497,"[{'Name': 'Irrigation and drainage'}, {'Name':...",N,OTHER,RE,[Rural development],0,MINISTRY OF AGRICULTURE AND PRODUCER ORGANISAT...,Second Emergency Agricultural Productivity Sup...,"10,6",2014-12-31T00:00:00Z,...,"[{'Percent': 40, 'Name': 'Agriculture, fishing...",August,"[{'code': '91', 'name': 'Global food crisis re...",Republic of Guinea,http://www.worldbank.org/projects/P128309/seco...,IBRD,Active,0,"[{'code': 'AI', 'name': 'Irrigation and draina...",{'$oid': '52b213b38594d8a2be17c971'}
498,[{'Name': 'Agricultural extension and research...,N,IBRD,PE,"[Rural development, Rural development, Rural d...",0,INDONESIAN AGENCY FOR AGRICULTURAL RESEARCH AN...,Sustainable Management of Agricultural Researc...,"10,10,10",2017-09-30T00:00:00Z,...,"[{'Percent': 80, 'Name': 'Agriculture, fishing...",August,"[{'code': '78', 'name': 'Rural services and in...",Republic of Indonesia,http://www.worldbank.org/projects/P117243/sust...,IBRD,Active,80000000,"[{'code': 'AB', 'name': 'Agricultural extensio...",{'$oid': '52b213b38594d8a2be17c972'}
499,"[{'Name': 'Urban Transport'}, {'Name': 'Public...",N,IDA,PE,"[Urban development, Human development, Trade a...",300000000,MINISTRY OF ROADS,KENYA: NATIONAL URBAN TRANSPORT IMPROVEMENT PR...,"9,8,5,4",2018-12-31T00:00:00Z,...,"[{'Percent': 79, 'Name': 'Transportation'}, {'...",August,"[{'code': '73', 'name': 'Municipal governance ...",Republic of Kenya,http://www.worldbank.org/projects/P126321/keny...,IBRD,Active,0,"[{'code': 'TC', 'name': 'Urban Transport'}, {'...",{'$oid': '52b213b38594d8a2be17c973'}

In [127]:
df.sort_values('idacommamt',ascending=False)['countryname'][0:10]

463    Federal Democratic Republic of Ethiopia
110            People's Republic of Bangladesh
476              Socialist Republic of Vietnam
340           Republic of the Union of Myanmar
461    Federal Democratic Republic of Ethiopia
288               Islamic Republic of Pakistan
108            People's Republic of Bangladesh
57                           Republic of India
65                                      Africa
465            People's Republic of Bangladesh
Name: countryname, dtype: object

In [128]:
m=df['mjtheme_namecode'].value_counts(ascending=False)[0:10]
m

[{'code': '11', 'name': 'Environment and natural resources management'}, {'code': '11', 'name': 'Environment and natural resources management'}]                                                                                12
[{'code': '8', 'name': 'Human development'}, {'code': '11', 'name': ''}]                                                                                                                                                        11
[{'code': '8', 'name': 'Human development'}, {'code': '8', 'name': 'Human development'}]                                                                                                                                         8
[{'code': '4', 'name': 'Financial and private sector development'}, {'code': '4', 'name': 'Financial and private sector development'}]                                                                                           6
[{'code': '2', 'name': 'Public sector governance'}, {'code': '2', 'name': 'Public sector governance'}, {'code': '2', 'name': 'Public sector governance'}]                                                                        6
[{'code': '8', 'name': 'Human development'}, {'code': '7', 'name': 'Social dev/gender/inclusion'}]                                                                                                                               5
[{'code': '8', 'name': 'Human development'}, {'code': '8', 'name': 'Human development'}, {'code': '8', 'name': 'Human development'}, {'code': '8', 'name': 'Human development'}, {'code': '8', 'name': 'Human development'}]     5
[{'code': '11', 'name': 'Environment and natural resources management'}, {'code': '11', 'name': ''}]                                                                                                                             5
[{'code': '11', 'name': 'Environment and natural resources management'}, {'code': '4', 'name': ''}]                                                                                                                              5
[{'code': '4', 'name': 'Financial and private sector development'}, {'code': '5', 'name': 'Trade and integration'}]                                                                                                              5
Name: mjtheme_namecode, dtype: int64

In [133]:
pd.DataFrame(m).fillna(method='ffill')

                                                    mjtheme_namecode
[{'code': '11', 'name': 'Environment and natura...                12
[{'code': '8', 'name': 'Human development'}, {'...                11
[{'code': '8', 'name': 'Human development'}, {'...                 8
[{'code': '4', 'name': 'Financial and private s...                 6
[{'code': '2', 'name': 'Public sector governanc...                 6
[{'code': '8', 'name': 'Human development'}, {'...                 5
[{'code': '8', 'name': 'Human development'}, {'...                 5
[{'code': '11', 'name': 'Environment and natura...                 5
[{'code': '11', 'name': 'Environment and natura...                 5
[{'code': '4', 'name': 'Financial and private s...                 5